### ISSUE TITLE
In __setitem__ convert to numpy arrays

### ISSUE THREAD

**Issue by ArvidJB** [Quansight/versioned-hdf5#26]
`h5py` converts anything passed into `__setitem__` into numpy arrays, we should do the same in versioned-hdf5:
```
In [8]: with h5py.File('foo.h5', 'w') as f:
   ...:     vf = VersionedHDF5File(f)
   ...:     with vf.stage_version('0') as sv:
   ...:         sv['bar'] = [1, 2, 3]
   ...:
```
This will complain about 
`AttributeError: 'list' object has no attribute 'dtype'`

**Comment by asmeurer** [comment]
I think this should be fixed.
