### ISSUE TITLE
test_mostly_appends_sparse is very slow

### ISSUE THREAD

**Issue by ArvidJB** [Quansight/versioned-hdf5#52]
Running `test_mostly_appends_sparse` against regular HDF5 without versioning takes about 2-3 seconds. Running it with versioning takes hours. Both are running 2500 transactions.

**Comment by ArvidJB** [comment]
Stopping in the debugger at random times points to this code
```
        for i in range(math.ceil(self.shape[0]/self.chunk_size)):
            for t in slice_map:
                r = range(*t)
                if i*self.chunk_size in r:
                    self.data_dict[i] = slice_map[t]
```
in `InMemoryDatasetID.__init__()`

**Comment by asmeurer** [comment]
Oh yeah, that's a quadratic algorithm, because I didn't want to work out the right way to do it at the time, but I never got back to fixing it. Should be straightforward to fix.

**Comment by ArvidJB** [comment]
Thanks @asmeurer !
It's actually worse than that, it's cubic: `r` is a `range` and the `in r` test iterates through the range...
