### ISSUE TITLE
Error with more than one nesting level

### ISSUE THREAD

**Issue by ArvidJB** [Quansight/versioned-hdf5#58]
This does not work
```
with h5py.File('foo.h5', 'w') as f:
    vf = VersionedHDF5File(f)
    with vf.stage_version('v0') as sv:
        sv.create_dataset('a/b', data=np.array([1, 2, 3]))
        print(sv['a/b'][:])
        sv.create_dataset('a/c/d', data=np.array([1, 2, 3]))
        print(sv['a/b'][:])
```
because creating 'a/c/d' seems to delete group 'a', probably because this line
```        dirname, data_name = pp.split(name)```
only splits off one level.

**Comment by asmeurer** [comment]
I see what is happening. In `create_group`, I incorrectly assume all the group levels do not yet exist.
